/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ServiceAreaRouteImport } from './routes/service-area'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TechnologyRouteImport } from './routes/technology'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaRoute = ServiceAreaRouteImport.update({
  id: '/service-area',
  path: '/service-area',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/service-area': typeof ServiceAreaRoute
  '/services': typeof ServicesRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/service-area': typeof ServiceAreaRoute
  '/services': typeof ServicesRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/service-area': typeof ServiceAreaRoute
  '/services': typeof ServicesRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/how-it-works'
    | '/service-area'
    | '/services'
    | '/technology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/how-it-works'
    | '/service-area'
    | '/services'
    | '/technology'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/how-it-works'
    | '/service-area'
    | '/services'
    | '/technology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ServiceAreaRoute: typeof ServiceAreaRoute
  ServicesRoute: typeof ServicesRoute
  TechnologyRoute: typeof TechnologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area': {
      id: '/service-area'
      path: '/service-area'
      fullPath: '/service-area'
      preLoaderRoute: typeof ServiceAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  ServiceAreaRoute: ServiceAreaRoute,
  ServicesRoute: ServicesRoute,
  TechnologyRoute: TechnologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
